version: '3'

services:
  distributor:
    build: .
    ports:
      - 8000:80
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=TRUE
      - KEY_PREFIX=ISO
      - REDIS_HOST=redis

  redis:
    image: redis:alpine